[package]
name = "klondike-rs"
version = "0.1.0"
authors = ["Chris Bouchard <chris@upliftinglemma.net>"]
edition = "2018"

[dependencies]
failure = "*"
failure_derive = "*"
itertools = "*"
rand = "*"

[dependencies.ncurses]
version = "*"
features = ["wide"]
