version: 2.1

orbs:
  rust: glotrade/rust@0.1.3

jobs:
  rust-tests-stable:
    description: |
      Run Cargo Tests: Stable
    executor: rustup-executor
    steps:
      - checkout
      - rust/update_toolchain:
          toolchain: stable
      - rust/clippy
      - rust/test

  rust-tests-nightly:
    description: |
      Run Cargo Tests: Nightly
    executor: rustup-executor
    steps:
      - checkout
      - rust/update_toolchain:
          toolchain: nightly
      - rust/clippy
      - rust/test

workflows:
  version: 2
  run-tests:
    jobs:
      - rust-tests-stable
      - rust-tests-nightly

