version: 2.1

executors:
  rustup-executor:
    docker:
      - image: liuchong/rustup:1.39.0

commands:
  setup-sccache:
    steps:
      - run:
          name: Install sccache
          command: |
            cargo install sccache
            # This configures Rust to use sccache.
            echo 'export "RUSTC_WRAPPER"="sccache"' >> $BASH_ENV
            # This is the maximum space sccache cache will use on disk.
            echo 'export "SCCACHE_CACHE_SIZE"="1G"' >> $BASH_ENV
            sccache --version
  restore-sccache-cache:
    steps:
      - restore_cache:
          name: Restore sccache cache
          key: sccache-cache-{{ .Environment.RUSTUP_TOOLCHAIN }}-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
  save-sccache-cache:
    steps:
      - save_cache:
          name: Save sccache cache
          # We use {{ epoch }} to always upload a fresh cache:
          # Of course, restore_cache will not find this exact key,
          # but it will fall back to the closest key (aka the most recent).
          # See https://discuss.circleci.com/t/add-mechanism-to-update-existing-cache-key/9014/13
          key: sccache-cache-{{ .Environment.RUSTUP_TOOLCHAIN }}-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths:
            - "~/.cache/sccache"

jobs:
  rust-tests-stable:
    description: |
      Run Cargo Tests: Stable
    executor: rustup-executor
    steps:
      - checkout
      - setup-sccache
      - restore-sccache-cache
      - run: cargo test
      - save-sccache-cache

  rust-tests-nightly:
    description: |
      Run Cargo Tests: Nightly
    executor: rustup-executor
    environment:
      RUSTUP_TOOLCHAIN: nightly
    steps:
      - checkout
      - setup-sccache
      - restore-sccache-cache
      - run: cargo test
      - save-sccache-cache

workflows:
  version: 2
  run-tests:
    jobs:
      - rust-tests-stable
      - rust-tests-nightly

