version: 2.1

commands:
  setup-rustup-toolchain:
    parameters:
      toolchain:
        description: Rustup Toolchain Name
        type: string
    steps:
      - run:
         name: |
           Setup Rust Toolchain: << parameters.toolchain >>
         command: |
           rustup toolchain install << paramters.toolchain >>
           echo 'export "RUSTUP_TOOLCHAIN"="<< parameters.toolchain >>"' >> $BASH_ENV

  setup-sccache:
    steps:
      - run:
          name: Install sccache
          command: |
            cargo install sccache
            # This configures Rust to use sccache.
            echo 'export "RUSTC_WRAPPER"="sccache"' >> $BASH_ENV
            # This is the maximum space sccache cache will use on disk.
            echo 'export "SCCACHE_CACHE_SIZE"="1G"' >> $BASH_ENV
            sccache --version
  restore-sccache-cache:
    steps:
      - restore_cache:
          name: Restore sccache cache
          key: sccache-cache-{{ .Environment.RUSTUP_TOOLCHAIN }}-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
  save-sccache-cache:
    steps:
      - save_cache:
          name: Save sccache cache
          # We use {{ epoch }} to always upload a fresh cache:
          # Of course, restore_cache will not find this exact key,
          # but it will fall back to the closest key (aka the most recent).
          # See https://discuss.circleci.com/t/add-mechanism-to-update-existing-cache-key/9014/13
          key: sccache-cache-{{ .Environment.RUSTUP_TOOLCHAIN }}-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths:
            - "~/.cache/sccache"

jobs:
  rust-tests:
    parameters:
      toolchain:
        description: Rustup Toolchain Name
        type: string
    description: |
      Run Cargo Tests: << parameters.toolchain >>
    docker:
      - image: liuchong/rustup
    steps:
      - checkout
      - setup-rustup-toolchain:
          toolchain: "<< parameters.toolchain >>"
      - setup-sccache
      - restore-sccache-cache
      - run: cargo test
      - save-sccache-cache

workflows:
  version: 2
  run-tests:
    jobs:
      - rust-tests:
          toolchain: stable
      - rust-tests:
          toolchain: nightly

