version: 2.1

executors:
  rustup-executor:
    docker:
      - image: liuchong/rustup:1.39.0

commands:
  cargo-test:
    steps:
      - run: cargo test

  cargo-version:
    steps:
      - run:
          name: Version Information
          command: |
            echo -n "Rustup Version: "
            rustup --version
            echo -n "Cargo Version: "
            cargo --version

  restore-cargo-cache:
    steps:
      - restore_cache:
          name: Restore Cargo Cache
          key: v1-cargo-deps-{{ checksum "Cargo.lock" }}

  save-cargo-cache:
    steps:
      - save_cache:
          key: v1-cargo-deps-{{ checksum "Cargo.lock" }}-{{ epoch }}
          paths:
            # Global cargo cache
            - /root/.cargo
            # Per-project cache
            - target

jobs:
  rust-tests-stable:
    description: |
      Run Cargo Tests: Stable
    executor: rustup-executor
    steps:
      - cargo-version
      - checkout
      - restore-cargo-cache
      - cargo-test
      - save-cargo-cache

  rust-tests-nightly:
    description: |
      Run Cargo Tests: Nightly
    executor: rustup-executor
    environment:
      RUSTUP_TOOLCHAIN: nightly
    steps:
      - cargo-version
      - checkout
      - restore-cargo-cache
      - cargo-test
      - save-cargo-cache

workflows:
  version: 2
  run-tests:
    jobs:
      - rust-tests-stable
      - rust-tests-nightly

